#UPdated the params reqruied for setting up DH parameters
/**:
  ros__parameters:
    joint_position_limits: [3.0, 1.5, 1.5, 1.5]
    end_effectot_twist_linear: [0.0,0.1,0.0]
    update_frequency: 20.0 #Hz
    move_duration: 2.0 #Secs

