RBE500 Final Project: manipulator::ManipulatorVLKROS Class Reference
manipulator::ManipulatorVLKROS Class Reference
ROS 2 node for Velocity level kinematics service.
#include <manipulator_vlk_ros.hpp>
Public Member Functions
ManipulatorVLKROS ()
Constructor for ManipulatorIKROS.
~ManipulatorVLKROS ()=default
Default destructor.
Private Member Functions
void initNodeParams ()
Initializes the node parameters.
void initSubscribers ()
Initializes the node subscribers.
void initServices ()
Initializes the node services.
void onSubscriberJointAngleCB (sensor_msgs::msg::JointState::ConstSharedPtr input_msg)
Callback for joint angle subscriber to process end effector pose.
void onEETwistServiceCB (const std::shared_ptr< rbe500_final_project_msgs::srv::GetEndEffectorTwist::Request > request, std::shared_ptr< rbe500_final_project_msgs::srv::GetEndEffectorTwist::Response > response)
Callback function for the End effector twist service.
void onJointVelServiceCB (const std::shared_ptr< rbe500_final_project_msgs::srv::GetJointVelocities::Request > request, std::shared_ptr< rbe500_final_project_msgs::srv::GetJointVelocities::Response > response)
Callback function for the Joint Velocities service.
Private Attributes
rclcpp::Subscription< sensor_msgs::msg::JointState >::SharedPtr joint_sub_
Joint angle subscriber.
rclcpp::Service< rbe500_final_project_msgs::srv::GetEndEffectorTwist >::SharedPtr ee_twist_server_
Service server for Enf Effector twist calculations.
rclcpp::Service< rbe500_final_project_msgs::srv::GetJointVelocities >::SharedPtr joint_vel_server_
Service server for Joint velocities calculations.
std::shared_ptr< manipulator::ManipulatorCore > manipulator_
Pointer to the manipulator core library instance.
Eigen::VectorXd link_length_
Vector containing link lengths of the manipulator.
Eigen::Vector4d joint_angles_
Vector containing joint angles.
Detailed Description
ROS 2 node for Velocity level kinematics service.
Provides a service interface to compute joint veloctities and end-effector twist
Constructor & Destructor Documentation
ManipulatorVLKROS()
manipulator::ManipulatorVLKROS::ManipulatorVLKROS ()
Constructor for ManipulatorIKROS.
~ManipulatorVLKROS()
manipulator::ManipulatorVLKROS::~ManipulatorVLKROS () default
Default destructor.
Member Function Documentation
initNodeParams()
void manipulator::ManipulatorVLKROS::initNodeParams () private
Initializes the node parameters.
Referenced by ManipulatorVLKROS().
initServices()
void manipulator::ManipulatorVLKROS::initServices () private
Initializes the node services.
Referenced by ManipulatorVLKROS().
initSubscribers()
void manipulator::ManipulatorVLKROS::initSubscribers () private
Initializes the node subscribers.
Referenced by ManipulatorVLKROS().
onEETwistServiceCB()
void manipulator::ManipulatorVLKROS::onEETwistServiceCB (const std::shared_ptr< rbe500_final_project_msgs::srv::GetEndEffectorTwist::Request > request, std::shared_ptr< rbe500_final_project_msgs::srv::GetEndEffectorTwist::Response > response) private
Callback function for the End effector twist service.
Parameters
request The service request containing the target joint_velocities
response The service response containing the computed End Effector twist
Referenced by initServices().
onJointVelServiceCB()
void manipulator::ManipulatorVLKROS::onJointVelServiceCB (const std::shared_ptr< rbe500_final_project_msgs::srv::GetJointVelocities::Request > request, std::shared_ptr< rbe500_final_project_msgs::srv::GetJointVelocities::Response > response) private
Callback function for the Joint Velocities service.
Parameters
request The service request containing the target end-effector twist
response The service response containing the computed joint velocities
Referenced by initServices().
onSubscriberJointAngleCB()
void manipulator::ManipulatorVLKROS::onSubscriberJointAngleCB (sensor_msgs::msg::JointState::ConstSharedPtr input_msg) private
Callback for joint angle subscriber to process end effector pose.
Parameters
input_msg The incoming joint state message
Referenced by initSubscribers().
Member Data Documentation
ee_twist_server_
rclcpp::Service<rbe500_final_project_msgs::srv::GetEndEffectorTwist>::SharedPtr manipulator::ManipulatorVLKROS::ee_twist_server_ private
Service server for Enf Effector twist calculations.
Referenced by initServices().
joint_angles_
Eigen::Vector4d manipulator::ManipulatorVLKROS::joint_angles_ private
Vector containing joint angles.
Referenced by ManipulatorVLKROS(), and onSubscriberJointAngleCB().
joint_sub_
rclcpp::Subscription<sensor_msgs::msg::JointState>::SharedPtr manipulator::ManipulatorVLKROS::joint_sub_ private
Joint angle subscriber.
Subscribes to /joint_angles topic and receives joint angles in radians
Referenced by initSubscribers().
joint_vel_server_
rclcpp::Service<rbe500_final_project_msgs::srv::GetJointVelocities>::SharedPtr manipulator::ManipulatorVLKROS::joint_vel_server_ private
Service server for Joint velocities calculations.
Referenced by initServices().
link_length_
Eigen::VectorXd manipulator::ManipulatorVLKROS::link_length_ private
Vector containing link lengths of the manipulator.
Referenced by initNodeParams(), and ManipulatorVLKROS().
manipulator_
std::shared_ptr<manipulator::ManipulatorCore> manipulator::ManipulatorVLKROS::manipulator_ private
Pointer to the manipulator core library instance.
Referenced by ManipulatorVLKROS(), onEETwistServiceCB(), onJointVelServiceCB(), and onSubscriberJointAngleCB().
The documentation for this class was generated from the following files:
include/rbe500_final_project/manipulator_vlk_ros.hpp
src/manipulator_vlk_ros.cpp