RBE500 Final Project: ManipulatorFollowActions Class Reference
ManipulatorFollowActions Class Reference
Class to control the manipulator through a sequence of predefined actions.
#include <manipulator_follow_actions.hpp>
Public Member Functions
ManipulatorFollowActions ()
Constructor for ManipulatorFollowActions.
void executeActionSequence ()
Execute the sequence of actions defined in the YAML configuration.
Private Member Functions
void loadConfig (const std::string &config_path)
Loads configuration from a YAML file.
void goToPosition (const std::string &position_name)
Moves the manipulator to a specified position.
void openGripper ()
Opens the gripper.
void closeGripper ()
Closes the gripper.
bool callIKService (const geometry_msgs::msg::Pose &pose, std::vector< double > &joint_angles)
Calls the IK service to get the joint angles for a given pose.
bool moveToJointPosition (const std::vector< double > &joint_angles)
Moves the manipulator to a specified joint position.
bool controlGripper (double position)
Controls the gripper to a specified position.
Private Attributes
rclcpp::Publisher< visualization_msgs::msg::Marker >::SharedPtr marker_pub_
Visualization marker publisher.
rclcpp::Client< rbe500_final_project_msgs::srv::GetJointAngles >::SharedPtr ik_client_
Service client for IK service.
rclcpp::Client< open_manipulator_msgs::srv::SetJointPosition >::SharedPtr joint_position_client_
Service client for joint position service.
rclcpp::Client< open_manipulator_msgs::srv::SetJointPosition >::SharedPtr gripper_client_
Service client for gripper service.
const double DEFAULT_WAIT_TIME =2.0
std::vector< double > joint_angles_
std::map< std::string, geometry_msgs::msg::Pose > pose_configs_
std::vector< ActionSequence > action_sequence_
Detailed Description
Class to control the manipulator through a sequence of predefined actions.
This class provides functionality to load and execute a sequence of manipulation actions defined in a YAML configuration file
Constructor & Destructor Documentation
ManipulatorFollowActions()
ManipulatorFollowActions::ManipulatorFollowActions ()
Constructor for ManipulatorFollowActions.
Member Function Documentation
callIKService()
bool ManipulatorFollowActions::callIKService (const geometry_msgs::msg::Pose & pose, std::vector< double > & joint_angles) private
Calls the IK service to get the joint angles for a given pose.
Parameters
pose The target pose
[out] joint_angles The resulting joint angles
Returns
true if the service call was successful, false otherwise
Referenced by goToPosition().
closeGripper()
void ManipulatorFollowActions::closeGripper () private
Closes the gripper.
Referenced by executeActionSequence().
controlGripper()
bool ManipulatorFollowActions::controlGripper (double position) private
Controls the gripper to a specified position.
Parameters
position The target gripper position
Returns
true if the service call was successful, false otherwise
Referenced by closeGripper(), and openGripper().
executeActionSequence()
void ManipulatorFollowActions::executeActionSequence ()
Execute the sequence of actions defined in the YAML configuration.
goToPosition()
void ManipulatorFollowActions::goToPosition (const std::string & position_name) private
Moves the manipulator to a specified position.
Parameters
position_name Name of the target position from configuration
Referenced by executeActionSequence().
loadConfig()
void ManipulatorFollowActions::loadConfig (const std::string & config_path) private
Loads configuration from a YAML file.
Parameters
config_path Path to the YAML configuration file
Referenced by ManipulatorFollowActions().
moveToJointPosition()
bool ManipulatorFollowActions::moveToJointPosition (const std::vector< double > & joint_angles) private
Moves the manipulator to a specified joint position.
Parameters
joint_angles The target joint angles
Returns
true if the service call was successful, false otherwise
Referenced by goToPosition().
openGripper()
void ManipulatorFollowActions::openGripper () private
Opens the gripper.
Referenced by executeActionSequence().
Member Data Documentation
action_sequence_
std::vector<ActionSequence> ManipulatorFollowActions::action_sequence_ private
Storage for action sequences
Referenced by executeActionSequence(), and loadConfig().
DEFAULT_WAIT_TIME
const double ManipulatorFollowActions::DEFAULT_WAIT_TIME =2.0 private
Default wait time for actions (seconds)
Referenced by loadConfig().
gripper_client_
rclcpp::Client<open_manipulator_msgs::srv::SetJointPosition>::SharedPtr ManipulatorFollowActions::gripper_client_ private
Service client for gripper service.
Referenced by controlGripper(), and ManipulatorFollowActions().
ik_client_
rclcpp::Client<rbe500_final_project_msgs::srv::GetJointAngles>::SharedPtr ManipulatorFollowActions::ik_client_ private
Service client for IK service.
Referenced by callIKService(), and ManipulatorFollowActions().
joint_angles_
std::vector<double> ManipulatorFollowActions::joint_angles_ private
Storage for joint angles
Referenced by controlGripper(), goToPosition(), and ManipulatorFollowActions().
joint_position_client_
rclcpp::Client<open_manipulator_msgs::srv::SetJointPosition>::SharedPtr ManipulatorFollowActions::joint_position_client_ private
Service client for joint position service.
Referenced by ManipulatorFollowActions(), and moveToJointPosition().
marker_pub_
rclcpp::Publisher<visualization_msgs::msg::Marker>::SharedPtr ManipulatorFollowActions::marker_pub_ private
Visualization marker publisher.
Referenced by callIKService(), and ManipulatorFollowActions().
pose_configs_
std::map<std::string, geometry_msgs::msg::Pose> ManipulatorFollowActions::pose_configs_ private
Storage for pose configurations
Referenced by goToPosition(), and loadConfig().
The documentation for this class was generated from the following files:
include/rbe500_final_project/manipulator_follow_actions.hpp
src/manipulator_follow_actions.cpp