RBE500 Final Project: helpers Namespace Reference
helpers Namespace Reference
Namespace containing utility functions for geometric and angular transformations.
Functions
template<typename T >
T normalize (const T &rad)
Function to normalize angle to make it between -pi to +pi range.
template<typename T >
T getRad (const T &deg)
Function to convert degrees to radians.
template<typename T >
T getDegrees (const T &rad)
Function to convert radians to degress.
Eigen::Vector3d convertRotationMatrixToRPY (const Eigen::Matrix3d &rotation)
Converts an Eigen rotation matrix to Roll-Pitch-Yaw angles.
geometry_msgs::msg::PoseStamped convertIsometry3dToPoseStamped (const Eigen::Isometry3d &transform, const std_msgs::msg::Header &header)
Converts an Eigen Isometry3d transform to a ROS PoseStamped message.
Eigen::Isometry3d convertPosetoIsometry3d (const geometry_msgs::msg::Pose &pose)
Converts a ROS Pose message to an Eigen Isometry3d transform.
visualization_msgs::msg::Marker convertPoseToMarker (const geometry_msgs::msg::Pose &pose, const std_msgs::msg::Header &header, std::string ns="pose_marker", int id=0, std::string marker_type="sphere")
Converts a ROS Pose message to a ROS Marker message.
Eigen::VectorXd convertStdVectorToEigenVector (const std::vector< double > &vec)
Converts a std::vector to an Eigen::VectorXd.
geometry_msgs::msg::Twist convertEigenVector6dToTwist (const Eigen::VectorXd &vec)
Converts an Eigen::Vector6d to a geometry_msgs::msg::Twist message.
geometry_msgs::msg::Twist convertStdVectorToTwist (const std::vector< double > &vec)
Converts a std::vector<double> to a geometry_msgs::msg::Twist message.
Eigen::VectorXd convertTwistToEigenVector6d (const geometry_msgs::msg::Twist &twist_msg)
Converts a geometry_msgs::msg::Twist message to an Eigen::Vector6d.
std::vector< double > convertEigenVectorToStdVector (const Eigen::VectorXd &eigen_vec)
Converts an Eigen::VectorXd to a std::vector<double>
double clamp (const double &value, const double &limit)
Clamps the input as per the limit.
Detailed Description
Namespace containing utility functions for geometric and angular transformations.
Function Documentation
clamp()
double helpers::clamp (const double & value, const double & limit) inline
Clamps the input as per the limit.
Parameters
value value to be clamped
limit absolute value of the limit
Returns
clamped_value
Referenced by manipulator::ManipulatorJPUpdaterROS::onSubscriberTargetJointVelocityCB().
convertEigenVector6dToTwist()
geometry_msgs::msg::Twist helpers::convertEigenVector6dToTwist (const Eigen::VectorXd & vec) inline
Converts an Eigen::Vector6d to a geometry_msgs::msg::Twist message.
Parameters
vec The input Eigen::Vector6d containing [vx, vy, vz, roll, pitch, yaw]
Returns
geometry_msgs::msg::Twist The converted Twist message
Referenced by manipulator::ManipulatorVLKROS::onEETwistServiceCB().
convertEigenVectorToStdVector()
std::vector<double> helpers::convertEigenVectorToStdVector (const Eigen::VectorXd & eigen_vec) inline
Converts an Eigen::VectorXd to a std::vector<double>
Parameters
eigen_vec The input Eigen::VectorXd to convert
Returns
std::vector<double> The converted std::vector
Referenced by manipulator::ManipulatorVLKROS::onJointVelServiceCB().
convertIsometry3dToPoseStamped()
geometry_msgs::msg::PoseStamped helpers::convertIsometry3dToPoseStamped (const Eigen::Isometry3d & transform, const std_msgs::msg::Header & header) inline
Converts an Eigen Isometry3d transform to a ROS PoseStamped message.
Parameters
transform The Eigen Isometry3d transform to convert
header The header information to be included in the PoseStamped message
Returns
geometry_msgs::msg::PoseStamped The converted pose message
Referenced by manipulator::ManipulatorFKROS::onSubscriberJointAngleCB().
convertPosetoIsometry3d()
Eigen::Isometry3d helpers::convertPosetoIsometry3d (const geometry_msgs::msg::Pose & pose) inline
Converts a ROS Pose message to an Eigen Isometry3d transform.
Parameters
pose The input ROS Pose message to convert
Returns
Eigen::Isometry3d The converted Eigen transform
Referenced by manipulator::ManipulatorIKROS::onServiceCB().
convertPoseToMarker()
visualization_msgs::msg::Marker helpers::convertPoseToMarker (const geometry_msgs::msg::Pose & pose, const std_msgs::msg::Header & header, std::string ns = "pose_marker", int id = 0, std::string marker_type = "sphere") inline
Converts a ROS Pose message to a ROS Marker message.
Parameters
pose The input ROS Pose message to convert
ns The namespace for the marker
id The ID for the marker
marker_type The type of marker to create ("arrow", "sphere", "cube")
Returns
visualization_msgs::msg::Marker The converted marker message
Referenced by ManipulatorFollowActions::callIKService().
convertRotationMatrixToRPY()
Eigen::Vector3d helpers::convertRotationMatrixToRPY (const Eigen::Matrix3d & rotation) inline
Converts an Eigen rotation matrix to Roll-Pitch-Yaw angles.
Code has been adapted from OpenManipulatorX_ROS2 project
Parameters
rotation Eigen 3x3 rotation matrix
Returns
Eigen::Vector3d containing RPY angles [roll, pitch, yaw]
See also
https://github.com/hylander2126/OpenManipulatorX_ROS2/blob/main/robotis_manipulator/src/robotis_manipulator/robotis_manipulator_math.cpp
Referenced by manipulator::ManipulatorCore::calcNewtonRaphsonIK(), and TEST().
convertStdVectorToEigenVector()
Eigen::VectorXd helpers::convertStdVectorToEigenVector (const std::vector< double > & vec) inline
Converts a std::vector to an Eigen::VectorXd.
Parameters
vec The input std::vector to convert
Returns
Eigen::VectorXd The converted Eigen vector
Referenced by manipulator::ManipulatorVLKROS::onEETwistServiceCB().
convertStdVectorToTwist()
geometry_msgs::msg::Twist helpers::convertStdVectorToTwist (const std::vector< double > & vec) inline
Converts a std::vector<double> to a geometry_msgs::msg::Twist message.
Parameters
vec The input std::vector<double> containing [vx, vy, vz, roll, pitch, yaw]
Returns
geometry_msgs::msg::Twist The converted Twist message
Referenced by ManipulatorMoveEE::moveEndEffector().
convertTwistToEigenVector6d()
Eigen::VectorXd helpers::convertTwistToEigenVector6d (const geometry_msgs::msg::Twist & twist_msg) inline
Converts a geometry_msgs::msg::Twist message to an Eigen::Vector6d.
Parameters
twist_msg The input Twist message containing linear and angular velocities
Returns
Eigen::Vector6d The converted Eigen vector
Referenced by manipulator::ManipulatorVLKROS::onJointVelServiceCB().
getDegrees()
template<typename T > T helpers::getDegrees (const T & rad) inline
Function to convert radians to degress.
Parameters
def Angle in radians
Returns
Normalized Angle in degrees (-pi to pi range)
getRad()
template<typename T > T helpers::getRad (const T & deg) inline
Function to convert degrees to radians.
Parameters
def Angle in degrees
Returns
Normalized Angle in radians (-pi to pi range)
normalize()
template<typename T > T helpers::normalize (const T & rad) inline
Function to normalize angle to make it between -pi to +pi range.
Parameters
rad Angle in radians
Returns
Normalized angle in radians
Referenced by getDegrees(), and getRad().